[pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py *_test.py
addopts = --cov=. --cov-report=html --cov-report=term -v -p no:warnings
pythonpath = .
DJANGO_ALLOW_ASYNC_UNSAFE = true
